### ISSUE TITLE
Make the js pages work (404, info, brand-guidelines)

### ISSUE THREAD

**Issue by olavea** [olavea/unlockopen.com#2]
- [x] Use actions instead of `boundActionCreators` as reported by console #4 
- [x] Use pageContext instead of `pathContext` as reported by console #5
- [x] Fix gatsby-plugin-typography problem #7
- [ ] Fix all console warnings #8

Check /404, /info and /brand-guidelines and fix any problems that might be reported.

I think the problems #4 and #5 above will go away when you have done Delete unused/unneeded code #6 n

**Comment by olavea** [comment]
Compiled with 1 warnings    in #8
